# Generated by Django 5.1.4 on 2025-03-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('finished', 'Finished'), ('semi-finished', 'Semi-Finished'), ('raw', 'Raw')], max_length=15)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('product_image', models.URLField(blank=True, max_length=500, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('unit_of_measure', models.CharField(choices=[('mtr', 'Meter'), ('mm', 'Millimeter'), ('ltr', 'Liter'), ('ml', 'Milliliter'), ('cm', 'Centimeter'), ('mg', 'Milligram'), ('gm', 'Gram'), ('unit', 'Unit'), ('pack', 'Pack')], max_length=5)),
                ('lead_time', models.PositiveSmallIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
